### PR TITLE
👷 Add pre_command input to CI job

### LINKED ISSUE #360: Support docs inside github artifact / url
Use case: https://github.com/huggingface/huggingface.js

There's a "docs" folder which is actually just generated docs from the source code.

It would be nice to not have to store it in the git repo, so doc-builder being able to download docs from an artificat or url would be great!

### PR DESCRIPTION
**Pull request by coyotte508**
Fix #360 

Slack: https://huggingface.slack.com/archives/C04U1CZQBQX/p1682775421137039 cc @xenova (hopefully it'll fix)

### CODE REVIEW

**Comment by coyotte508** [comment]
Merging to try out in @huggingface/js

**Comment by xenova** [comment]
Sweet!

**Comment by coyotte508** [comment]
messed up updating build_pr_documentation - fixed in https://github.com/huggingface/doc-builder/commit/550d6e3709742a7a3366f03151d8eed210a2dc44

**Comment by sgugger** [comment]
Thanks for quickly fixing the break in the PR documentation, but can we maybe wait for a review before merging something like this? It is **always** possible to test a branch by installing doc-builder from that branch or executing the workflow template from a branch, so the argument of "merging quickly to help xxx" is not a good one.

**Pull request merged**
