### PR TITLE
Added/Changed/Depreacted directives

### PR DESCRIPTION
**Pull request by mishig25**
Implemented directives for: `Added, Changed, Deprecated`

Related to https://github.com/huggingface/doc-builder/issues/173

In the screenshots, please find proposed syntax & results (UIs) wdyt?

Screenshot 2022-05-31 at 11 05 54
Screenshot 2022-05-31 at 11 05 45
Screenshot 2022-05-31 at 11 05 38

- [x] todo: add imports

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Looks great to me!
I think we should import those new components [here](https://github.com/huggingface/doc-builder/blob/d6126583f078b8b7be60a1c1fbbf2af9853c3eef/src/doc_builder/convert_md_to_mdx.py#L31) though, no?

**Comment by mishig25** [comment]
indeed, added the imports & merging it

**Comment by albertvillanova** [comment]
Thanks @mishig25.

I'm testing it.

**Comment by albertvillanova** [comment]
Issue reported:
- https://github.com/huggingface/datasets/pull/4429#issuecomment-1145810820

No special formatting appears:
- https://moon-ci-docs.huggingface.co/docs/datasets/pr_4429/en/package_reference/builder_classes#datasets.DatasetBuilder

**Pull request merged**
