### PR TITLE
Optimize html tag replace regex (Fixes #331)

### LINKED ISSUE #331: preview taking a lot of time
Hello!

I have trouble running the preview command.
First, I run the build command:
```sh
doc-builder build transformers docs/source/en/ --build_dir ~/tmp/test-build
```

Afterwards, I run:
```sh
doc-builder preview transformers ~/tmp/test-build
```

Which leads me to the following prompt:
```sh
Building the MDX files:  31%|█████████████████████████████████████████████▌                                                                                                       | 79/258 [01:53<19:06,  6.40s/it]
```

And this process would take infinitely long, it didn't even finish after 8 hours. I am not sure whether this is expected or some bug.

NB: it gets stuck at around 77/258, before this everything is super fast.

I am running M1 Mac OS.

Thanks!

### PR DESCRIPTION
**Pull request by xenova**
Building/previewing the docs for Transformers.js takes >12 minutes on my system and ~15 minutes with GitHub actions:
image

After investigating further, its due to this line of code, which consumes >99% of build time:

https://github.com/huggingface/doc-builder/blob/c59346e932a62f9edb9bfbb68c6ac8096ee50282/src/doc_builder/convert_md_to_mdx.py#L85-L87

The regex is very strict, and requires that the start and end tag match. However, in practice, this is not necessary at all (and in fact, will break on slightly malformed html tags). A better (and much faster approach) is to just replace the `<` character of any valid start/end tag (regardless of whether they have a matching pair). That is the purpose of this PR.

---

Before:
```bash
Building the MDX files: 100%|██████████| 30/30 [10:35<00:00, 22.71s/it]
```

After:
```bash
Building the MDX files: 100%|██████████| 30/30 [00:00<00:00, 124.46it/s]
```

which is a ~3000x speedup.

---

This fixes https://github.com/huggingface/doc-builder/issues/331, which reported the same issue.

### CODE REVIEW

**Comment by xenova** [comment]
Although it passes all the unit tests, I think we should run before and after this change on the transformers docs and perform a `diff` to make sure nothing crazy happens.

**Comment by xenova** [comment]
Unrelated failing tests fixed [here](https://github.com/huggingface/doc-builder/pull/374)

**Comment by xenova** [comment]
@mishig25 I see it fails on the case:
```
 122 |  <p>TP is almost always used within a single node. That is TP size <= gpus per node.</p>
```

Should be simple to fix, I just need to add a positive lookahead for any closing tag

**Review by sgugger — APPROVED** [review]
This looks simpler to me, thanks! Still would like for @mishig25 to double-check since he originally wrote this part, to make sure we are not forgetting any other use-case.

**Comment by xenova** [comment]
> This looks simpler to me, thanks! Still would like for @mishig25 to double-check since he originally wrote this part, to make sure we are not forgetting any other use-case.

Agreed! :) Other than https://github.com/huggingface/transformers/pull/23646, everything seems to convert correctly. To be sure, we can perhaps run a diff between the two?

**Comment by sgugger** [comment]
Note that the tool is used across all Hugging Face repos, so there might be some issues specific to other repos too.

**Comment by xenova** [comment]
> Note that the tool is used across all Hugging Face repos, so there might be some issues specific to other repos too.

Right - it's probably best to do what @mishig25 did [here](https://github.com/huggingface/transformers/pull/23625) for all the repos listed [here](https://huggingface.co/docs).

**Comment by xenova** [comment]
Failing tests related to https://github.com/huggingface/doc-builder/pull/374 (which have been fixed)

**Comment by mishig25** [comment]
oh I see, @xenova could you update this PR branch with the `main` branch ?

**Comment by radames** [comment]
I came to  this issue while trying to preview `xenova/transformers.js` docs. Is there a workaround to speed up the preview using `docs-preview` ? right now it taking considering amount of time just to preview a couple of docs. thanks

**Comment by sgugger** [comment]
@mishig25 friendly ping.

**Comment by xenova** [comment]
My docs on transformers.js builds are getting quite long (e.g., the [latest one](https://github.com/xenova/transformers.js/actions/runs/5930418148/job/16080116152) is ~21 mins), so it would be nice to get this merged 😅 @mishig25

I could switch to use this branch in the meantime, but I think other repos will also benefit from this.

**Comment by sgugger** [comment]
We can address any of Mishig's comments in a followup PR if needed. Let's not block everyone as doc-building is quite long on all Transformers projects!

**Comment by sgugger** [comment]
Went from 30 minutes to 12 minutes for Transformers :-)

**Comment by radames** [comment]
amazing @xenova super fast now!!

**Comment by Wauplin** [comment]
Hey, I just found out about this change as it just broke `huggingface_hub`'s CI. I have a docstring [here](https://github.com/huggingface/huggingface_hub/blob/111fdbe3508a8727da7acf17ee84ec613608b801/src/huggingface_hub/file_download.py#L1026) in which both a `"<"` and a `">"` are used but not as HTML tag:

```
...
... Small files (<5MB) are duplicated in ...
...
... README.md -> ../../blobs/d7edf6bd2a681fb0175f7735299831ee1b22b812 ....
```

The new regex considers it as an HTML tag which ends up breaking the doc build as the `<` char is not escaped properly.

@xenova Given how great the speed improvement of your change is, I'll try to update the regex but still keep your approach. I'll keep you updated :)

**Pull request merged**
