### PR TITLE
Add description for anchor links

### PR DESCRIPTION
**Pull request by mishig25**

### CODE REVIEW

**Review by julien-c — COMMENTED** [review]
cool feature! in which doc-builder PR was this implemented, out of curiosity?

**Comment by mishig25** [comment]
@julien-c https://github.com/huggingface/doc-builder/blob/d6126583f078b8b7be60a1c1fbbf2af9853c3eef/src/doc_builder/build_doc.py#L280-L287

the pr is #15

**Comment by julien-c** [comment]
Thank you!! I didn't know that feature, it's very useful.

**Comment by mishig25** [comment]
I guess we added this feature before we wrote the README, but luckily we document it now 😊

**Pull request merged**
