### PR TITLE
Fix args parsing when argument doesn't have a type

### PR DESCRIPTION
**Pull request by Wauplin**
(testing things for timm)

Explanation:
1. docstring is parsed => parameters section is located from the `Args:` (or `Parameters:`) title
2. then, each arg section is detected. The logic detect new args from the indentation. The first line of an arg looks like this:
```
filter_bias_and_bn (*str*, _optional_):  If True, bias, norm layer parameters (...)
```

3. then, the arg first line is reformatted to
```
- **filter_bias_and_bn** (*str*, _optional_) -- If True, bias, norm layer parameters (...)
```
=> a regex splits the line around `":"`
=> another regex detects the arg name "`filter_bias_and_bn`" and adds the `** **` around it
=> finally, a string concatenation is applied to replace the `:` by a `--`
**This is the step that got modified in this PR.**

4. Later in the process, if an arg doesn't start with `- **(...)`, it is removed from the docstring, hence not appearing in the docs.

---
What this PR does is to update the regex from step 3. that adds `** **` with a substitution. The regex was `r"^\s*(\S+)(\s)"` which does not match when an argument has no extra information apart its name. This is for example the case for many `timm` docstrings that follow google style (-ish).

```
param_group_fn: Optional function to create custom parameter groups.
```
=> regex does not detect a new space => `- **(...)` is not added => the arg is removed from the docs
This PR allows for no extra space by adding a simple `?` to the regex :smile:

### CODE REVIEW

**Comment by Wauplin** [comment]
Doc builder seems to have an issue on timm's PR https://github.com/huggingface/pytorch-image-models/pull/2337 (http 404 on the link even though it successfully passed in CI). But "locally it works as expected":

## From https://huggingface.co/docs/timm/main/en/reference/optimizers:

image

## With this PR:

image

**Comment by mishig25** [comment]
rebase with main to fix the failing tests ?

**Comment by Wauplin** [comment]
Yep, CI's green now :)

**Review by coyotte508 — APPROVED** [review]
:see_no_evil:

**Comment by coyotte508** [comment]
Maybe add a testcase ?

**Review by mishig25 — APPROVED** [review]
lgtm !

yep, feel free to add test cases

**Comment by Wauplin** [comment]
Added a test case in https://github.com/huggingface/doc-builder/pull/535/commits/9be24eab2f84ecc30f59f15a3bc8cb46323cd391. Let's merge :)

**Comment by mishig25** [comment]
merging once the tests finish passing

**Pull request merged**
