### PR TITLE
Unescape <YouTube

### PR DESCRIPTION
**Pull request by mishig25**
Fixes error where <YouTube becomes alt;ltYoutube

### CODE REVIEW

**Comment by mishig25** [comment]
merging it so that the builds are getting built correctly
cc: @sgugger @LysandreJik

**Comment by Pierrci** [comment]
Interesting, were all the videos broken as a result? Or only some of them?

**Comment by Pierrci** [comment]
ok saw the other PRs!

**Review by sgugger — COMMENTED** [review]
Thanks for fixing this!

**Pull request merged**
