### PR TITLE
:bug: use proper package_name in doc-builder build cmd

### LINKED ISSUE #305: Build docs using package name that differs from repo name
I am currently working on building the timm docs, which are at `rwightman/pytorch-image-models`. The package name itself is `timm`. 

As far as I understand, we use the `package` input to specify the repo name. It's used to clone the repo here:

https://github.com/huggingface/doc-builder/blob/4ac0cc8454bb5e5c875e1e11abf86b68473ca7b4/.github/workflows/build_pr_documentation.yml#L56

Apparently `package` is again used to build the documentation here:

https://github.com/huggingface/doc-builder/blob/4ac0cc8454bb5e5c875e1e11abf86b68473ca7b4/.github/workflows/build_pr_documentation.yml#L143

Why aren't we using the `package_name` env variable that was updated to be `package` if it wasn't provided to do the above `doc-builder build` command? I think this is what's going wrong with my PR [here](https://github.com/rwightman/pytorch-image-models/actions/runs/3176196617/jobs/5175209231). It leads to `ModuleNotFoundError: No module named 'pytorch-image-models'`.

Am I missing something/doing something wrong?

CC @mishig25 @osanseviero

### PR DESCRIPTION
**Pull request by nateraw**
Resolves #305

### CODE REVIEW

**Comment by nateraw** [comment]
seems to be a GitHub actions outage right now, so can't test this til that's resolved

**Comment by nateraw** [comment]
Tested in `timm`

- [Successful Action](https://github.com/rwightman/pytorch-image-models/actions/runs/3191602155/jobs/5208108952) (with `--not_python_module` flag removed, which proves it works)

Still should probably check it works with other packages

**Comment by mishig25** [comment]
thanks a lot for working on this! testing it at: https://github.com/huggingface/transformers/pull/19372

**Review by mishig25 — APPROVED** [review]
lgtm! [test succeeded](https://github.com/huggingface/transformers/pull/19372#issuecomment-1269621138)

merge whenever you'd like to

**Pull request merged**
